version: "3"
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15671:15671"
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"
      - "4369:4369"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    container_name: rabbitmq
    networks:
      my-network:

  config-service:
    image: tlsdnwn55/kkakka-config-service:dev
    ports:
      - "8888:8888"
    environment:
      spring.rabbitmq.host: rabbitmq
      spring.cloud.config.server.git.default-label: main
      # spring.profiles.active: dev
    container_name: config-service
    depends_on:
      - rabbitmq
    networks:
      my-network:

  main-service:
    image: tlsdnwn55/kkakka-main-service:dev
    ports:
      - "9000:9000"
    environment:
      spring.cloud.config.uri: http://config-service:8888
      spring.rabbitmq.host: rabbitmq
      spring.profiles.active: dev
    container_name: main-service
    depends_on:
      - config-service
    networks:
      my-network:

  discovery-service:
    image: tlsdnwn55/kkakka-discovery-service:dev
    ports:
      - "8761:8761"
    environment:
      spring.cloud.config.uri: http://config-service:8888
    container_name: discovery-service
    depends_on:
      - config-service
    networks:
      my-network:

  apigateway-service:
    image: tlsdnwn55/kkakka-apigateway-service:dev
    ports:
      - "8000:8000"
    environment:
      spring.cloud.config.uri: http://config-service:8888
      spring.rabbitmq.host: rabbitmq
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka/
    container_name: apigateway-service
    depends_on:
      - discovery-service
    networks:
      my-network:

  mysqldb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: kkakka
      MYSQL_DATABASE: kkakkadb
      MYSQL_USER: kkakka
      MYSQL_PASSWORD: 1234
    networks:
      my-network:

networks:
  my-network:
    external: true
    name: kkakka-network
