server:
  port: 9001
  servlet:
    context-path: /api

spring:
  application:
    name: auth-service
  mvc:
    throw-exception-if-no-handler-found: true
  output:
    ansi:
      enabled: always
  profiles:
    active: dev
    include: oauth, datasource
