import Head from "next/head";
import Image from "next/image";
import Title from "../components/common/Title";
import Slider from "../components/main/Slider";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>kka-kka</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Title title="과자 사러 과자" />

      <Slider />

      <style jsx>{`
        .contents {
          margin-top: 35px;
        }
      `}</style>
    </>
  );
}
