import Head from "next/head";
import { useState } from "react";
import Title from "../components/common/Title";
import Visual from "../components/main/Visual";
import Youtube from "../components/main/Youtube";
import Introduction from "../components/main/Introduction";
import Recomm from "../components/main/Recomm";

export default function Home() {
  const [tab, setTab] = useState("리뷰");

  function handleTab(text) {
    setTab(text);
  }

  return (
    <>
      <Head>
        <title>kka-kka</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title title="과자 사러 과자" />
      <Visual />
      <Recomm tab={tab} handleTab={handleTab} />
      <Youtube />

      <Introduction />
    </>
  );
}
